import "~/styles/globals.css";

import { type Metadata } from "next";
import { GeistMono } from 'geist/font/mono'

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
